import postgres from "postgres";

const url = process.env.DATABASE_URL ?? "";

const HOUSE_CAMPAIGNS = [
  {
    id: "house-services-001",
    internal_name: "AkarProMax Services House",
    advertiser_name: "AkarProMax",
    campaign_type: "house",
    status: "active",
    media_type: "image",
    media_url: "data:image/svg+xml," + encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400" viewBox="0 0 600 400"><rect fill="#0B214C" width="600" height="400"/><text x="300" y="160" text-anchor="middle" fill="#D8AF55" font-size="36" font-family="Arial,sans-serif" font-weight="bold">AkarProMax</text><text x="300" y="210" text-anchor="middle" fill="#FFFFFF" font-size="20" font-family="Arial,sans-serif">خدمات هندسية احترافية</text><text x="300" y="260" text-anchor="middle" fill="#1769FF" font-size="16" font-family="Arial,sans-serif">www.akarpromax.com</text></svg>`),
    channels: '["website"]',
    eyebrow_ar: "إعلان", eyebrow_en: "Ad", eyebrow_tr: "Reklam",
    title_ar: "خدمات هندسية احترافية", title_en: "Professional Engineering Services", title_tr: "Profesyonel Mühendislik Hizmetleri",
    accent_ar: "AkarProMax", accent_en: "AkarProMax", accent_tr: "AkarProMax",
    description_ar: "استكشف أفضل المكاتب الهندسية في منطقتك", description_en: "Discover top engineering offices in your area", description_tr: "Bölgenizdeki en iyi mühendislik ofislerini keşfedin",
    cta_ar: "اكتشف الآن", cta_en: "Discover Now", cta_tr: "Şimdi Keşfet",
    target_url: "/services",
    countries: "[]", cities: "[]", languages: '["ar","en","tr"]', devices: '["desktop","mobile"]',
    priority: 1, weight: 5, start_at: null, end_at: null,
    section_scopes: '["services","global"]', page_types: '["services"]',
    placements: "[]", domains: "[]", region_ids: "[]", district_ids: "[]",
    latitude: null, longitude: null, radius_km: null,
    target_all_countries: 1, target_all_regions: 1, target_all_cities: 1, target_all_districts: 1,
    entity_type: null, entity_ids: "[]", category_ids: "[]",
    property_types: "[]", service_categories: "[]", office_types: "[]", tool_categories: "[]",
    operating_systems: "[]", daily_start_time: null, daily_end_time: null,
    days_of_week: "[]", rotation_group: null,
    pricing_model: "house", price: 0, budget: 0, daily_budget: 0, spent_amount: 0,
    max_impressions: 0, max_clicks: 0, frequency_cap_per_user: 0, frequency_cap_period: "day",
    approval_status: "approved", is_active: 1, is_sponsored: 0, is_featured: 0, is_fallback: 1, is_global: 1,
    total_impressions: 0, total_unique_impressions: 0, total_clicks: 0, total_unique_clicks: 0, total_conversions: 0,
  },
  {
    id: "house-properties-001",
    internal_name: "AkarProMax Properties House",
    advertiser_name: "AkarProMax",
    campaign_type: "house",
    status: "active",
    media_type: "image",
    media_url: "data:image/svg+xml," + encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400" viewBox="0 0 600 400"><rect fill="#1769FF" width="600" height="400"/><text x="300" y="160" text-anchor="middle" fill="#FFFFFF" font-size="36" font-family="Arial,sans-serif" font-weight="bold">AkarProMax</text><text x="300" y="210" text-anchor="middle" fill="#D8AF55" font-size="20" font-family="Arial,sans-serif">عقارات للبيع والإيجار</text><text x="300" y="260" text-anchor="middle" fill="#FFFFFF" font-size="16" font-family="Arial,sans-serif">www.akarpromax.com</text></svg>`),
    channels: '["website"]',
    eyebrow_ar: "إعلان", eyebrow_en: "Ad", eyebrow_tr: "Reklam",
    title_ar: "عقارات للبيع والإيجار", title_en: "Properties for Sale & Rent", title_tr: "Satılık ve Kiralık Emlak",
    accent_ar: "AkarProMax", accent_en: "AkarProMax", accent_tr: "AkarProMax",
    description_ar: "تصفح آلاف العقارات في جميع المناطق", description_en: "Browse thousands of properties across all regions", description_tr: "Tüm bölgelerde binlerce gayrimenkulü keşfedin",
    cta_ar: "تصفح الآن", cta_en: "Browse Now", cta_tr: "Şimdi Göz At",
    target_url: "/properties",
    countries: "[]", cities: "[]", languages: '["ar","en","tr"]', devices: '["desktop","mobile"]',
    priority: 1, weight: 5, start_at: null, end_at: null,
    section_scopes: '["properties","global"]', page_types: '["properties"]',
    placements: "[]", domains: "[]", region_ids: "[]", district_ids: "[]",
    latitude: null, longitude: null, radius_km: null,
    target_all_countries: 1, target_all_regions: 1, target_all_cities: 1, target_all_districts: 1,
    entity_type: null, entity_ids: "[]", category_ids: "[]",
    property_types: "[]", service_categories: "[]", office_types: "[]", tool_categories: "[]",
    operating_systems: "[]", daily_start_time: null, daily_end_time: null,
    days_of_week: "[]", rotation_group: null,
    pricing_model: "house", price: 0, budget: 0, daily_budget: 0, spent_amount: 0,
    max_impressions: 0, max_clicks: 0, frequency_cap_per_user: 0, frequency_cap_period: "day",
    approval_status: "approved", is_active: 1, is_sponsored: 0, is_featured: 0, is_fallback: 1, is_global: 1,
    total_impressions: 0, total_unique_impressions: 0, total_clicks: 0, total_unique_clicks: 0, total_conversions: 0,
  },
  {
    id: "house-tools-001",
    internal_name: "AkarProMax Tools House",
    advertiser_name: "AkarProMax",
    campaign_type: "house",
    status: "active",
    media_type: "image",
    media_url: "data:image/svg+xml," + encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400" viewBox="0 0 600 400"><rect fill="#D8AF55" width="600" height="400"/><text x="300" y="160" text-anchor="middle" fill="#0B214C" font-size="36" font-family="Arial,sans-serif" font-weight="bold">AkarProMax</text><text x="300" y="210" text-anchor="middle" fill="#0B214C" font-size="20" font-family="Arial,sans-serif">أدوات هندسية مجانية</text><text x="300" y="260" text-anchor="middle" fill="#0B214C" font-size="16" font-family="Arial,sans-serif">www.akarpromax.com</text></svg>`),
    channels: '["website"]',
    eyebrow_ar: "إعلان", eyebrow_en: "Ad", eyebrow_tr: "Reklam",
    title_ar: "أدوات هندسية مجانية", title_en: "Free Engineering Tools", title_tr: "Ücretsiz Mühendislik Araçları",
    accent_ar: "AkarProMax", accent_en: "AkarProMax", accent_tr: "AkarProMax",
    description_ar: "حاسبات مساحة وخرسانة وتحويل إحداثيات", description_en: "Area, concrete calculators and coordinate converter", description_tr: "Alan ve beton hesaplayıcılar ve koordinat dönüştürücü",
    cta_ar: "جرّب الآن", cta_en: "Try Now", cta_tr: "Şimdi Dene",
    target_url: "/tools",
    countries: "[]", cities: "[]", languages: '["ar","en","tr"]', devices: '["desktop","mobile"]',
    priority: 1, weight: 5, start_at: null, end_at: null,
    section_scopes: '["tools","global"]', page_types: '["tools"]',
    placements: "[]", domains: "[]", region_ids: "[]", district_ids: "[]",
    latitude: null, longitude: null, radius_km: null,
    target_all_countries: 1, target_all_regions: 1, target_all_cities: 1, target_all_districts: 1,
    entity_type: null, entity_ids: "[]", category_ids: "[]",
    property_types: "[]", service_categories: "[]", office_types: "[]", tool_categories: "[]",
    operating_systems: "[]", daily_start_time: null, daily_end_time: null,
    days_of_week: "[]", rotation_group: null,
    pricing_model: "house", price: 0, budget: 0, daily_budget: 0, spent_amount: 0,
    max_impressions: 0, max_clicks: 0, frequency_cap_per_user: 0, frequency_cap_period: "day",
    approval_status: "approved", is_active: 1, is_sponsored: 0, is_featured: 0, is_fallback: 1, is_global: 1,
    total_impressions: 0, total_unique_impressions: 0, total_clicks: 0, total_unique_clicks: 0, total_conversions: 0,
  },
  {
    id: "house-general-001",
    internal_name: "AkarProMax General House",
    advertiser_name: "AkarProMax",
    campaign_type: "house",
    status: "active",
    media_type: "image",
    media_url: "data:image/svg+xml," + encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400" viewBox="0 0 600 400"><rect fill="#0B214C" width="600" height="400"/><rect x="50" y="50" width="500" height="300" rx="20" fill="none" stroke="#D8AF55" stroke-width="3"/><text x="300" y="180" text-anchor="middle" fill="#D8AF55" font-size="32" font-family="Arial,sans-serif" font-weight="bold">AkarProMax</text><text x="300" y="230" text-anchor="middle" fill="#FFFFFF" font-size="18" font-family="Arial,sans-serif">منصة العقارات والخدمات الهندسية</text><text x="300" y="275" text-anchor="middle" fill="#1769FF" font-size="14" font-family="Arial,sans-serif">www.akarpromax.com</text></svg>`),
    channels: '["website"]',
    eyebrow_ar: "إعلان", eyebrow_en: "Ad", eyebrow_tr: "Reklam",
    title_ar: "منصة العقارات والخدمات الهندسية", title_en: "Real Estate & Engineering Platform", title_tr: "Emlak ve Mühendislik Platformu",
    accent_ar: "AkarProMax", accent_en: "AkarProMax", accent_tr: "AkarProMax",
    description_ar: "كل ما تحتاجه للعقارات والهندسة في مكان واحد", description_en: "Everything you need for real estate and engineering in one place", description_tr: "Gayrimenkul ve mühendislik için ihtiyacınız olan her şey tek bir yerde",
    cta_ar: "سجّل الآن", cta_en: "Sign Up Now", cta_tr: "Hemen Kayıt Ol",
    target_url: "/",
    countries: "[]", cities: "[]", languages: '["ar","en","tr"]', devices: '["desktop","mobile"]',
    priority: 0, weight: 3, start_at: null, end_at: null,
    section_scopes: '["global"]', page_types: '["home"]',
    placements: "[]", domains: "[]", region_ids: "[]", district_ids: "[]",
    latitude: null, longitude: null, radius_km: null,
    target_all_countries: 1, target_all_regions: 1, target_all_cities: 1, target_all_districts: 1,
    entity_type: null, entity_ids: "[]", category_ids: "[]",
    property_types: "[]", service_categories: "[]", office_types: "[]", tool_categories: "[]",
    operating_systems: "[]", daily_start_time: null, daily_end_time: null,
    days_of_week: "[]", rotation_group: null,
    pricing_model: "house", price: 0, budget: 0, daily_budget: 0, spent_amount: 0,
    max_impressions: 0, max_clicks: 0, frequency_cap_per_user: 0, frequency_cap_period: "day",
    approval_status: "approved", is_active: 1, is_sponsored: 0, is_featured: 0, is_fallback: 1, is_global: 1,
    total_impressions: 0, total_unique_impressions: 0, total_clicks: 0, total_unique_clicks: 0, total_conversions: 0,
  },
  {
    id: "house-offices-001",
    internal_name: "AkarProMax Offices House",
    advertiser_name: "AkarProMax",
    campaign_type: "house",
    status: "active",
    media_type: "image",
    media_url: "data:image/svg+xml," + encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400" viewBox="0 0 600 400"><rect fill="#1A3A5C" width="600" height="400"/><rect x="150" y="80" width="300" height="240" rx="10" fill="#0B214C" stroke="#D8AF55" stroke-width="2"/><text x="300" y="180" text-anchor="middle" fill="#D8AF55" font-size="28" font-family="Arial,sans-serif" font-weight="bold">AkarProMax</text><text x="300" y="220" text-anchor="middle" fill="#FFFFFF" font-size="16" font-family="Arial,sans-serif">دليل المكاتب الهندسية</text><text x="300" y="255" text-anchor="middle" fill="#1769FF" font-size="13" font-family="Arial,sans-serif">www.akarpromax.com</text></svg>`),
    channels: '["website"]',
    eyebrow_ar: "إعلان", eyebrow_en: "Ad", eyebrow_tr: "Reklam",
    title_ar: "دليل المكاتب الهندسية", title_en: "Engineering Offices Directory", title_tr: "Mühendislik Ofisleri Dizini",
    accent_ar: "AkarProMax", accent_en: "AkarProMax", accent_tr: "AkarProMax",
    description_ar: "ابحث عن أفضل المكاتب الهندسية", description_en: "Find the best engineering offices", description_tr: "En iyi mühendislik ofislerini bulun",
    cta_ar: "استكشف", cta_en: "Explore", cta_tr: "Keşfet",
    target_url: "/offices",
    countries: "[]", cities: "[]", languages: '["ar","en","tr"]', devices: '["desktop","mobile"]',
    priority: 1, weight: 4, start_at: null, end_at: null,
    section_scopes: '["organizations","global"]', page_types: '["offices"]',
    placements: "[]", domains: "[]", region_ids: "[]", district_ids: "[]",
    latitude: null, longitude: null, radius_km: null,
    target_all_countries: 1, target_all_regions: 1, target_all_cities: 1, target_all_districts: 1,
    entity_type: null, entity_ids: "[]", category_ids: "[]",
    property_types: "[]", service_categories: "[]", office_types: "[]", tool_categories: "[]",
    operating_systems: "[]", daily_start_time: null, daily_end_time: null,
    days_of_week: "[]", rotation_group: null,
    pricing_model: "house", price: 0, budget: 0, daily_budget: 0, spent_amount: 0,
    max_impressions: 0, max_clicks: 0, frequency_cap_per_user: 0, frequency_cap_period: "day",
    approval_status: "approved", is_active: 1, is_sponsored: 0, is_featured: 0, is_fallback: 1, is_global: 1,
    total_impressions: 0, total_unique_impressions: 0, total_clicks: 0, total_unique_clicks: 0, total_conversions: 0,
  },
  {
    id: "house-home-001",
    internal_name: "AkarProMax Home Hero House",
    advertiser_name: "AkarProMax",
    campaign_type: "house",
    status: "active",
    media_type: "image",
    media_url: "data:image/svg+xml," + encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="400" viewBox="0 0 1200 400"><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="#0B214C"/><stop offset="100%" stop-color="#1769FF"/></linearGradient></defs><rect fill="url(#bg)" width="1200" height="400"/><text x="600" y="160" text-anchor="middle" fill="#D8AF55" font-size="48" font-family="Arial,sans-serif" font-weight="bold">AkarProMax</text><text x="600" y="220" text-anchor="middle" fill="#FFFFFF" font-size="24" font-family="Arial,sans-serif">منصة العقارات والخدمات الهندسية</text><text x="600" y="280" text-anchor="middle" fill="#FFFFFF" font-size="18" font-family="Arial,sans-serif" opacity="0.8">www.akarpromax.com</text></svg>`),
    channels: '["website"]',
    eyebrow_ar: "إعلان", eyebrow_en: "Ad", eyebrow_tr: "Reklam",
    title_ar: "مرحباً بك في AkarProMax", title_en: "Welcome to AkarProMax", title_tr: "AkarProMax'e Hoş Geldiniz",
    accent_ar: "المنصة الأولى للعقارات والخدمات الهندسية", accent_en: "#1 Platform for Real Estate & Engineering", accent_tr: "Gayrimenkul ve Mühendislik İçin #1 Platform",
    description_ar: "اكتشف عقارات للبيع والإيجار وخدمات هندسية متعددة في مكان واحد", description_en: "Discover properties for sale & rent and multi-disciplinary engineering services in one place", description_tr: "Satılık ve kiralık gayrimenkulleri ve çok disiplinli mühendislik hizmetlerini tek bir yerde keşfedin",
    cta_ar: "ابدأ الآن", cta_en: "Get Started", cta_tr: "Başlayın",
    target_url: "/",
    countries: "[]", cities: "[]", languages: '["ar","en","tr"]', devices: '["desktop","mobile"]',
    priority: 2, weight: 5, start_at: null, end_at: null,
    section_scopes: '["global"]', page_types: '["home"]',
    placements: '["hero"]', domains: "[]", region_ids: "[]", district_ids: "[]",
    latitude: null, longitude: null, radius_km: null,
    target_all_countries: 1, target_all_regions: 1, target_all_cities: 1, target_all_districts: 1,
    entity_type: null, entity_ids: "[]", category_ids: "[]",
    property_types: "[]", service_categories: "[]", office_types: "[]", tool_categories: "[]",
    operating_systems: "[]", daily_start_time: null, daily_end_time: null,
    days_of_week: "[]", rotation_group: null,
    pricing_model: "house", price: 0, budget: 0, daily_budget: 0, spent_amount: 0,
    max_impressions: 0, max_clicks: 0, frequency_cap_per_user: 0, frequency_cap_period: "day",
    approval_status: "approved", is_active: 1, is_sponsored: 0, is_featured: 0, is_fallback: 1, is_global: 1,
    total_impressions: 0, total_unique_impressions: 0, total_clicks: 0, total_unique_clicks: 0, total_conversions: 0,
  },
];

async function seedHouseAds() {
  const client = postgres(url, { ssl: "require", prepare: false });
  try {
    const cols = Object.keys(HOUSE_CAMPAIGNS[0]);
    const colList = cols.join(", ");
    for (const c of HOUSE_CAMPAIGNS) {
      const vals = Object.values(c);
      const placeholders = cols.map((_, i) => `$${i + 1}`).join(", ");
      await client.unsafe(
        `INSERT INTO ad_campaigns (${colList}) VALUES (${placeholders}) ON CONFLICT (id) DO NOTHING`,
        vals,
      );
    }
    console.log("Seeded " + HOUSE_CAMPAIGNS.length + " house campaigns into ad_campaigns");
  } finally {
    await client.end();
  }
}

seedHouseAds().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
